### ISSUE TITLE
Master: No module database.info

### ISSUE THREAD

**Issue by kathrine-swe** [CS-Helper-Helpers/cs_helper#12]
No module named database.info

`.../cs_helper(master) » python3 cs_helper/cs_helper.py                
Traceback (most recent call last):
  File "cs_helper/cs_helper.py", line 13, in <module>
    from intent_classifier.intent_classifier import IntentClassifier
  File ".../intent_classifier/__init__.py", line 1, in <module>
    from .intent_classifier import IntentClassifier
  File ".../intent_classifier/intent_classifier.py", line 12, in <module>
    import database.engine as db
  File ".../database/__init__.py", line 1, in <module>
    from .engine import getBotDBEngine
  File ".../database/engine.py", line 2, in <module>
    import database.info as info
ModuleNotFoundError: No module named 'database.info'`

**Comment by kathrine-swe** [comment]
The info file is not pushed to the GitHub repository. If you need it, a hardcopy lives in the CS Helper's (user) cs_helper project.
